<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Casualties_Hub</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\CasualtiesHub.ico</ApplicationIcon>
    <Version>0.0.6-pre.8.2</Version>
    <AssemblyVersion>0.0.6.82</AssemblyVersion>
    <FileVersion>0.0.6.82</FileVersion>
    <InformationalVersion>0.0.6-pre.8.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="Helpers\" />
    <Folder Include="View Models\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\PapaZuck.png" />
    <Resource Include="Assets\CasualtiesHub.png" />
    <Resource Include="Assets\CreditMeow.jpg" />
    <Resource Include="Assets\CreditExp3238.png" />
    <Resource Include="Assets\CreditYou1Are0Ic.png" />
    <Resource Include="Assets\CreditMarly.png" />
    <Content Include="Services\DependencyCatalog.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Services\IncompatibilityCatalog.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Developer Console.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Installation.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.4.txt">
      <Link>Version 0.0.4.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.4.1.txt">
      <Link>Version 0.0.4.1.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.5.txt">
      <Link>Version 0.0.5.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.5-pre.1.txt">
      <Link>Version 0.0.5-pre.1.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.1.txt">
      <Link>Version 0.0.6-pre.1.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.2.txt">
      <Link>Version 0.0.6-pre.2.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.3.txt">
      <Link>Version 0.0.6-pre.3.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.4.txt">
      <Link>Version 0.0.6-pre.4.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.5.txt">
      <Link>Version 0.0.6-pre.5.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.6.txt">
      <Link>Version 0.0.6-pre.6.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.7.txt">
      <Link>Version 0.0.6-pre.7.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.8.txt">
      <Link>Version 0.0.6-pre.8.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.8.1.txt">
      <Link>Version 0.0.6-pre.8.1.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Release Notes\Version 0.0.6-pre.8.2.txt">
      <Link>Version 0.0.6-pre.8.2.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.0" />
    <PackageReference Include="Mono.Cecil" Version="0.11.5" />
  </ItemGroup>

</Project>
