<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\Casualties Hub\Assets\CasualtiesHub.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Casualties_Hub_Installer</RootNamespace>
    <AssemblyName>Casualties Hub Setup Wizard</AssemblyName>
    <Version>0.0.0</Version>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <FileVersion>0.0.0.0</FileVersion>
    <InformationalVersion>Wizard 0.0-pre.1</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\Casualties Hub\Assets\CasualtiesHub.png" Link="Assets\CasualtiesHub.png" />
  </ItemGroup>
</Project>
